Namespace Media

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>17/02/2014 16:03:04</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Deimos\_Media\Enums\WMT_CODEC_INFO_TYPE.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Deimos\_Media\Enums\WMT_CODEC_INFO_TYPE.tt", "1")> _
	Public Enum WMT_CODEC_INFO_TYPE As System.Int32

		''' <summary>WMT_CODECINFO_AUDIO</summary>
		WMT_CODECINFO_AUDIO = 0

		''' <summary>WMT_CODECINFO_VIDEO</summary>
		WMT_CODECINFO_VIDEO = 1

		''' <summary>WMT_CODECINFO_UNKNOWN</summary>
		WMT_CODECINFO_UNKNOWN = 16777215

	End Enum

End Namespace