Namespace Media

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>17/02/2014 16:03:03</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Deimos\_Media\Enums\WMT_ATTR_DATATYPE.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Deimos\_Media\Enums\WMT_ATTR_DATATYPE.tt", "1")> _
	Public Enum WMT_ATTR_DATATYPE As System.Int32

		''' <summary>WMT_TYPE_DWORD</summary>
		WMT_TYPE_DWORD = 0

		''' <summary>WMT_TYPE_STRING</summary>
		WMT_TYPE_STRING = 1

		''' <summary>WMT_TYPE_BINARY</summary>
		WMT_TYPE_BINARY = 2

		''' <summary>WMT_TYPE_BOOL</summary>
		WMT_TYPE_BOOL = 3

		''' <summary>WMT_TYPE_QWORD</summary>
		WMT_TYPE_QWORD = 4

		''' <summary>WMT_TYPE_WORD</summary>
		WMT_TYPE_WORD = 5

		''' <summary>WMT_TYPE_GUID</summary>
		WMT_TYPE_GUID = 6

	End Enum

End Namespace