''' <summary></summary>
''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
''' <generator-date>17/02/2014 16:02:01</generator-date>
''' <generator-functions>1</generator-functions>
''' <generator-source>Deimos\General\Enums\OfficeApplication.tt</generator-source>
''' <generator-version>1</generator-version>
<System.CodeDom.Compiler.GeneratedCode("Deimos\General\Enums\OfficeApplication.tt", "1")> _
Public Enum OfficeApplication As System.Int32

	''' <summary>Indicates no Application</summary>
	None = 0

	''' <summary>Indicates Application should be Microsoft Excel</summary>
	Excel = 1

	''' <summary>Indicates Application should be Microsoft Word</summary>
	Word = 2

	''' <summary>Indicates Application should be Microsoft Visio</summary>
	Visio = 3

End Enum