''' <summary></summary>
''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
''' <generator-date>17/02/2014 16:02:02</generator-date>
''' <generator-functions>1</generator-functions>
''' <generator-source>Deimos\General\Enums\OfficePageState.tt</generator-source>
''' <generator-version>1</generator-version>
<System.CodeDom.Compiler.GeneratedCode("Deimos\General\Enums\OfficePageState.tt", "1")> _
Public Enum OfficePageState As System.Int32

	''' <summary>Indicates no State, e.g. no Page</summary>
	None = 0

	''' <summary>Indicates Page was already Open</summary>
	Existing = 1

	''' <summary>Indicates Page was Created</summary>
	Created = 2

End Enum