''' <summary></summary>
''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
''' <generator-date>17/02/2014 16:02:02</generator-date>
''' <generator-functions>1</generator-functions>
''' <generator-source>Deimos\General\Enums\OutputLanguage.tt</generator-source>
''' <generator-version>1</generator-version>
<System.CodeDom.Compiler.GeneratedCode("Deimos\General\Enums\OutputLanguage.tt", "1")> _
Public Enum OutputLanguage As System.Int32

	''' <summary>Defines the Output Language as Visual Basic</summary>
	VisualBasic = 1

	''' <summary>Defines the Output Language as C# (C-Sharp)</summary>
	CSharp = 2

	''' <summary>Defines the Output Languages as J# (J-Sharp)</summary>
	JSharp = 3

End Enum