Namespace Excel

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>17/02/2014 16:02:50</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Deimos\_Excel\Enums\HorizontalAlignment.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Deimos\_Excel\Enums\HorizontalAlignment.tt", "1")> _
	Public Enum HorizontalAlignment As System.Int32

		''' <summary>Horizontal Align the Element on the Left</summary>
		Left = 1

		''' <summary>Horizontal Align the Element in the Center</summary>
		Center = 2

		''' <summary>Horizontal Align the Element on the Right</summary>
		Right = 3

	End Enum

End Namespace