Namespace Excel

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>17/02/2014 16:02:51</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Deimos\_Excel\Enums\VerticalAlignment.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Deimos\_Excel\Enums\VerticalAlignment.tt", "1")> _
	Public Enum VerticalAlignment As System.Int32

		''' <summary>Vertical Align the Element at the Top</summary>
		Top = 1

		''' <summary>Vertical Align the Element in the Center</summary>
		Center = 2

		''' <summary>Vertical Align the Element at the Bottom</summary>
		Bottom = 3

	End Enum

End Namespace